### api 1
POST http://localhost:3001/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

### api 2
POST http://localhost:3001/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

### api 3
GET http://localhost:3001/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY1ODA1NDQ3fQ.CuPi3Xf2ntwvbiLurIxttSGMpW-juXoRQ1T1ekqukDo

### api 4
GET http://localhost:3001/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY1ODA1NDQ3fQ.CuPi3Xf2ntwvbiLurIxttSGMpW-juXoRQ1T1ekqukDo

### api 5
GET http://localhost:3001/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY1ODA1NDQ3fQ.CuPi3Xf2ntwvbiLurIxttSGMpW-juXoRQ1T1ekqukDo

### api 6
GET http://localhost:3001/tweets/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY1ODA1NDQ3fQ.CuPi3Xf2ntwvbiLurIxttSGMpW-juXoRQ1T1ekqukDo

### api 7
GET http://localhost:3001/tweets/1/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY1ODA1NDQ3fQ.CuPi3Xf2ntwvbiLurIxttSGMpW-juXoRQ1T1ekqukDo

### api 8
GET http://localhost:3001/tweets/1/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY1ODA1NDQ3fQ.CuPi3Xf2ntwvbiLurIxttSGMpW-juXoRQ1T1ekqukDo

### api 9
GET http://localhost:3001/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY1ODA1NDQ3fQ.CuPi3Xf2ntwvbiLurIxttSGMpW-juXoRQ1T1ekqukDo

### api 10
POST http://localhost:3001/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY1ODA1NDQ3fQ.CuPi3Xf2ntwvbiLurIxttSGMpW-juXoRQ1T1ekqukDo
Content-Type: application/json

{
   "tweet": "The Mornings Walked 10 km are like it..."
}

### api 11
DELETE http://localhost:3001/tweets/:tweetId/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY1ODA1NDQ3fQ.CuPi3Xf2ntwvbiLurIxttSGMpW-juXoRQ1T1ekqukDo


